### ISSUE TITLE
I beg you to create a video tutorial of the full process please.

### ISSUE THREAD

**Issue by BeinfMdFahim** [slundi/RatioUp#6]
**### I am a noob,kindly make a video tutorial about the total installation process pleaseeeeeee.**

**Comment by slundi** [comment]
Hello
For now I'm fixing bugs and improving it a little. I'll improve the documentation later.
What OS are you using?

**Comment by BeinfMdFahim** [comment]
Ubuntu 22.04

**Comment by slundi** [comment]
Doc upgraded, closing issue
