### ISSUE TITLE
Docker doesn't work's

### ISSUE THREAD

**Issue by Jack74r** [slundi/RatioUp#9]
Hi
What is the state of the development of RatioUp ?

I try with docker on x64 server but looks not workin. 

My compose : 

  ratio-up:
    image: slundi/ratioup:latest
    container_name: ratio-up
    restart: unless-stopped
    network_mode: "service:gluetun"
    tty: true
    environment:
      - PUID=1000
      - PGID=100
      - SERVER_ADDR = "0.0.0.0:8070"
      - LOG_LEVEL = "INFO"
      - MIN_UPLOAD_RATE = 8192
      - MAX_UPLOAD_RATE = 2097152
      - MIN_DOWNLOAD_RATE = 8192
      - MAX_DOWNLOAD_RATE = 16777216
      - TORRENT_DIR = "/torrents"
      - CLIENT = "Transmission_3_00"
    volumes:
      - /docker-compose/ratio-up:/mnt
    depends_on:
      - gluetun
 

Container always restarting.
the log : 

> exec /app/RatioUp: exec format error
> exec /app/RatioUp: exec format error

in while ..

I also tried with sha amd64 but same issue : image: slundi/ratioup:latest@sha256:05041ed31809c1a0d4a7f0e6b9dcbe6a3c073430083bed88bd8e7a72e1e427f0

Thank

**Comment by slundi** [comment]
I'll drop docker support, see #7
